/**
 * Demo: Behavioral Analysis System
 * Shows the powerful insights generated by the new analyzer
 */

const behavioralAnalyzer = require('./backend/src/services/behavioralAnalyzer');

// Sample data for different developer types
const sampleProfiles = {
  builder: {
    repo_count: 45,
    stars: 1250,
    forks: 340,
    languages: { JavaScript: 45000, Python: 32000, TypeScript: 28000 },
    commit_pattern: 'consistent',
    builder_score: 85,
    explorer_score: 30,
    debugger_score: 60,
    perfectionist_score: 75,
    hustler_score: 40
  },
  
  explorer: {
    repo_count: 120,
    stars: 890,
    forks: 156,
    languages: { Rust: 8000, Go: 12000, Haskell: 5000, Swift: 9000, Kotlin: 7000 },
    commit_pattern: 'spiky',
    builder_score: 25,
    explorer_score: 95,
    debugger_score: 45,
    perfectionist_score: 35,
    hustler_score: 50
  },
  
  hustler: {
    repo_count: 28,
    stars: 2100,
    forks: 580,
    languages: { JavaScript: 67000, 'C#': 23000, PHP: 19000 },
    commit_pattern: 'rapid',
    builder_score: 60,
    explorer_score: 55,
    debugger_score: 40,
    perfectionist_score: 30,
    hustler_score: 90
  }
};

console.log('🧠 BEHAVIORAL ANALYSIS DEMO\n');
console.log('=' .repeat(50));

Object.entries(sampleProfiles).forEach(([type, data]) => {
  console.log(`\n🎯 ${type.toUpperCase()} PROFILE:`);
  console.log('-'.repeat(30));
  
  const analysis = behavioralAnalyzer.analyze(data);
  
  console.log(`\n📖 CORE INSIGHT:`);
  console.log(`"${analysis.coreInsight}"`);
  
  console.log(`\n💣 TRUTH BOMBS:`);
  analysis.truthBombs.forEach((bomb, i) => {
    console.log(`${i + 1}. ${bomb}`);
  });
  
  console.log(`\n💪 STRENGTHS:`);
  analysis.strengths.forEach((strength, i) => {
    console.log(`• ${strength}`);
  });
  
  console.log(`\n🔍 BLIND SPOTS:`);
  analysis.blindSpots.forEach((spot, i) => {
    console.log(`• ${spot}`);
  });
  
  console.log(`\n🌱 GROWTH SUGGESTIONS:`);
  analysis.growthSuggestions.forEach((suggestion, i) => {
    console.log(`• ${suggestion}`);
  });
  
  console.log(`\n🏷️  IDENTITY:`);
  console.log(`"${analysis.identityStatement}"`);
  
  console.log('\n' + '='.repeat(50));
});

console.log('\n✨ Try it yourself!');
console.log('📡 API: http://localhost:5000/api/behavioral/:username');
console.log('🌐 Frontend: http://localhost:5173');
