/**
 * Demo: GitHub Profile Roast Generator
 * Shows the spicy roasts generated by the new system
 */

const behavioralAnalyzer = require('./backend/src/services/behavioralAnalyzer');

// Sample profiles for different roast scenarios
const sampleProfiles = {
  overachiever: {
    repo_count: 150,
    stars: 5000,
    forks: 1200
  },
  
  underappreciated: {
    repo_count: 45,
    stars: 12,
    forks: 3
  },
  
  minimalist: {
    repo_count: 3,
    stars: 250,
    forks: 45
  },
  
  loneWolf: {
    repo_count: 25,
    stars: 180,
    forks: 0
  },
  
  oneHitWonder: {
    repo_count: 8,
    stars: 2100,
    forks: 560
  }
};

console.log('🔥 GITHUB PROFILE ROAST GENERATOR\n');
console.log('=' .repeat(50));

Object.entries(sampleProfiles).forEach(([type, data]) => {
  console.log(`\n🎯 ${type.toUpperCase()} SCENARIO:`);
  console.log('-'.repeat(30));
  
  console.log(`📊 Stats: ${data.repo_count} repos, ${data.stars} stars, ${data.forks} forks`);
  console.log(`⭐ Avg stars: ${data.repo_count > 0 ? Math.floor(data.stars / data.repo_count) : 0}`);
  
  const roasts = behavioralAnalyzer.generateRoast(data);
  
  console.log(`\n🔥 ROASTS:`);
  roasts.forEach((roast, i) => {
    console.log(`${i + 1}. ${roast}`);
  });
  
  console.log('\n' + '='.repeat(50));
});

console.log('\n✨ Try it yourself!');
console.log('📡 Roast API: http://localhost:5000/api/roast/:username');
console.log('🧠 Behavioral API: http://localhost:5000/api/behavioral/:username');
console.log('🌐 Frontend: http://localhost:5173');

// Test with real user
console.log('\n🔥 TESTING WITH OCTOCAT:');
const octocatData = {
  repo_count: 8,
  stars: 22166,
  forks: 580
};

const octocatRoasts = behavioralAnalyzer.generateRoast(octocatData);
console.log('📊 Octocat Stats: 8 repos, 22166 stars, 580 forks');
console.log('🔥 Octocat Roasts:');
octocatRoasts.forEach((roast, i) => {
  console.log(`${i + 1}. ${roast}`);
});
